---
name: default
kind: pipeline
type: docker

steps:
- name: test
  image: python
  commands:
  - apt-get update && apt-get install -y libcodec2-dev 
  - pip install numpy Cython
  - pip install .
  - pip install -r requirements.txt.gitpycodec2
  - python -m unittest discover -v
