---
name: default
kind: pipeline
type: docker

steps:
- name: build
  image: plugins/docker
  trigger:
    event:
    - cron
    cron:
    - weekly
  settings:
    repo: registry2.tarxvf.tech/mike/pym17_builder
    registry: registry2.tarxvf.tech
    username: mike
    password: 
      from_secret: registry2_password
    #target: build
- name: test
  pull: always
  image: registry2.tarxvf.tech/mike/pym17_builder
  commands:
  - pip install -r requirements_debian_10.txt
  - python -m unittest discover -v 
