---
name: default
kind: pipeline
type: docker

steps:
- name: build
  image: plugins/docker
  settings:
    repo: registry2.tarxvf.tech/mike/pym17_builder
    registry: registry2.tarxvf.tech
    username: mike
    password: 
      from_secret: registry2_password
    #target: build

- name: test
  pull: always
  image: registry2.tarxvf.tech/mike/pym17_builder
  commands:
  - pip install --upgrade pip numpy Cython wheel setuptools
  - pip install -r requirements_debian_10.txt
  - python -m unittest discover -v


image_pull_secrets:
- dockerconfigjson
