---
name: default
kind: pipeline
type: docker

steps:
- name: test
  image: python
  commands:
  - apt-get update && apt-get install -y libcodec2-dev libcodec2 codec2
  - pip install numpy Cython
  - pip install .
  - python -m unittest discover -v
