---
name: default
kind: pipeline
type: docker

steps:
- name: test
  image: python
  commands:
  - apt-get install codec2
  - pip install numpy Cython
  - pip install .
  - python -m unittest discover -v
