---
name: default
kind: pipeline
type: docker

steps:
- name: build
  image: plugins/docker
  trigger:
    event:
    - cron
    cron:
    - weekly
  when:
    event:
      include:
        - tag
        - promote
  settings:
    repo: registry2.tarxvf.tech/mike/pym17_builder
    registry: registry2.tarxvf.tech
    username: mike
    password: 
      from_secret: registry2_password
    #target: build
- name: test_and_build
  pull: always
  image: registry2.tarxvf.tech/mike/pym17_builder
  commands:
  - pip install -r requirements_debian_10.txt
  - python -m unittest discover -v 
- name: pypi_publish
  image: plugins/pypi
  distributions:
  - sdist
  - bdist_wheel
  when:
    branch:
      include:
      - push_pypi
  settings:
    username:
      from_secret: pypi_username
    password:
      from_secret: pypi_password
- name: test_install
  image: registry2.tarxvf.tech/mike/pym17_builder
  commands:
  - pip install m17
  #- python -m m17.sanity_check ; /bin/true
  - pip install m17[Codec2]
  #- python -m m17.sanity_check
  when:
    branch:
      include:
      - push_pypi
